# Start from the latest golang base image
FROM golang:latest as builder

LABEL maintainer="James Jarvis <git@jamesjarvis.io>"

RUN mkdir /build 
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o send cmd/rabbitmq-tutorial/send/main.go


######## Start a new stage from scratch #######
FROM scratch

COPY --from=builder /build/send /send

CMD ["./send"]