version: '3.7'
services:
  # colly-db:
  #   image: "postgres"
  #   env_file:
  #     - database.env
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - colly-db-data:/var/lib/postgresql/data/
  #   networks:
  #     - db
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - database.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "database:pgsql-server"
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - database.env
    ports:
      - "6060:6060"
    restart: on-failure
    depends_on:
      - database
    networks:
      - db

volumes:
  # colly-db-data:
  database-data:
  pgadmin-data:

networks:
  db: