version: '3.7'
services:
  # colly-db:
  #   image: "postgres"
  #   env_file:
  #     - database.env
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - colly-db-data:/var/lib/postgresql/data/
  #   networks:
  #     - db
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - database.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "database:pgsql-server"
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  # crawler:
  #   image: jjhaslanded/web-graph-crawler
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - database.env
  #   ports:
  #     - "6060:6060"
  #   restart: on-failure
  #   depends_on:
  #     - database
  #   networks:
  #     - db
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"

volumes:
  # colly-db-data:
  database-data:
  pgadmin-data:
  rabbitmq-data:

networks:
  db:
