version: '3.9'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - database.env
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    links:
      - "database:pgsql-server"
    depends_on:
      - database
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
  link-processor:
    image: jjhaslanded/link-processor
    build:
      context: .
      dockerfile: Dockerfile-link-processor
    restart: on-failure
    stop_grace_period: 30s
    env_file:
      - database.env
    environment:
      QUEUE_DATA: "/queue_data"
    volumes:
      - ./data/queue:/queue_data
    depends_on:
      - database
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# volumes:
#   database-data:
#   pgadmin-data:

networks:
  db:
