# Start from the latest golang base image
FROM golang:alpine as builder

LABEL maintainer="James Jarvis <git@jamesjarvis.io>"

RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

RUN mkdir /build 
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download
RUN go mod verify

# Copy the source from the current directory to the Working Directory inside the container
COPY cmd/ cmd/
COPY pkg/ pkg/

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o linkProcessor cmd/link-processor/main.go


######## Start a new stage from scratch #######
FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /build/linkProcessor /linkProcessor

CMD ["./linkProcessor"]